--- #YAML:1.0
name:               Image-Base-Imager
version:            11
abstract:           Image::Base on PNG files using Imager.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Image::Base:  1.16
    Imager:       0.39
    perl:         5.004
    Test:         0
resources:
    homepage:  http://user42.tuxfamily.org/image-base-imager/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
        - xt
        - devel
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            Test::Weaken:  2.000
